/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

function escapeStringRegexp(string) {
	if (typeof string !== 'string') {
		throw new TypeError('Expected a string');
	}

	// Escape characters with special meaning either inside or outside character sets.
	// Use a simple backslash escape when it’s always valid, and a `\xnn` escape when the simpler form would be disallowed by Unicode patterns’ stricter grammar.
	return string
		.replace(/[|\\{}()[\]^$+*?.]/g, '\\$&')
		.replace(/-/g, '\\x2d');
}

const newLineRegex = /(?:\n)/g;
class MyPlugin extends obsidian.Plugin {
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            console.log("loading plugin");
            this.addCommand({
                id: "find-and-replace-in-selection",
                name: "Find And Replace",
                editorCallback: (editor) => {
                    new FindAndReplaceModal(this.app, editor).open();
                },
            });
        });
    }
    onunload() {
        console.log("unloading plugin");
    }
}
class FindAndReplaceModal extends obsidian.Modal {
    constructor(app, editor) {
        super(app);
        this.shouldRestoreSelection = true;
        this.editor = editor;
    }
    onOpen() {
        let { contentEl, titleEl, editor, modalEl } = this;
        modalEl.addClass("find-and-replace-modal");
        titleEl.setText("Find and Replace in Selection");
        const rowClass = "row";
        const createInterfaceInputRow = (label, placeholder) => {
            const containerEl = document.createElement("div");
            containerEl.addClass(rowClass);
            const targetEl = document.createElement("div");
            targetEl.addClass("input-wrapper");
            const labelEl = document.createElement("div");
            labelEl.addClass("input-label");
            labelEl.setText(label);
            containerEl.appendChild(labelEl);
            containerEl.appendChild(targetEl);
            const component = new obsidian.TextComponent(targetEl);
            component.setPlaceholder(placeholder);
            contentEl.append(containerEl);
            return component;
        };
        const submitButtonTarget = document.createElement("div");
        submitButtonTarget.addClass("submit-button-wrapper");
        submitButtonTarget.addClass("row");
        const findInputComponent = createInterfaceInputRow("Find", "Text");
        const replaceWithInputComponent = createInterfaceInputRow("Replace With", "Replacement");
        const submitButtonComponent = new obsidian.ButtonComponent(submitButtonTarget);
        submitButtonComponent.setButtonText("Replace All");
        submitButtonComponent.setCta();
        submitButtonComponent.onClick(() => {
            const search = new RegExp(escapeStringRegexp(findInputComponent.getValue()), "g");
            // We make the special new line characters visible by escaping the '\' such that the '\n' will be detected
            const cleanedSelection = editor
                .getSelection()
                .replace(newLineRegex, "\\n");
            const count = (cleanedSelection.match(search) || []).length;
            if (count > 0) {
                const replacementText = cleanedSelection.replace(search, replaceWithInputComponent.getValue()).replace("\\n", "\n");
                // We convert any un-replaced new line characters back to their original state
                const selectionStart = editor.getCursor("from");
                editor.replaceSelection(replacementText);
                // We re-select the selected text (just for nicer user experience)
                editor.setSelection(selectionStart, editor.offsetToPos(editor.posToOffset(selectionStart) + replacementText.length));
            }
            this.close();
            new obsidian.Notice(`Made ${count} replacements`);
        });
        contentEl.appendChild(submitButtonTarget);
    }
    onClose() {
        let { contentEl } = this;
        contentEl.empty();
    }
}

module.exports = MyPlugin;


/* nosourcemap */